// =============================================================================
// MumbleManager
// Author:  Gerald Hull, W1VE
// Date:    April 14, 2026
// License: MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// =============================================================================

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MumbleManager.Data;

#nullable disable

namespace MumbleManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MumbleManager.Models.ChannelTemplate", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("CreatedUtc").HasColumnType("TEXT");
                b.Property<DateTime>("ModifiedUtc").HasColumnType("TEXT");
                b.Property<string>("RootChildrenJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("RootChildren")
                    .HasDefaultValue("[]");
                b.HasKey("Id");
                b.ToTable("ChannelTemplates");
            });

            modelBuilder.Entity("MumbleManager.Models.SshHostEntry", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("DisplayName").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Host").IsRequired().HasColumnType("TEXT");
                b.Property<int>("SshPort").HasColumnType("INTEGER");
                b.Property<string>("Username").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Password").IsRequired().HasColumnType("TEXT");
                b.Property<string>("IceSecret").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Hosts");
            });

            modelBuilder.Entity("MumbleManager.Models.VirtualServerCache", b =>
            {
                b.Property<int>("RowId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("HostId").IsRequired().HasColumnType("TEXT");
                b.Property<int>("ServerId").HasColumnType("INTEGER");
                b.Property<int>("Port").HasColumnType("INTEGER");
                b.Property<string>("ServerName").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ServerPassword").IsRequired().HasColumnType("TEXT");
                b.Property<string>("DefaultChannel").IsRequired().HasColumnType("TEXT");
                b.Property<string>("WelcomeMessage").IsRequired().HasColumnType("TEXT");
                b.Property<bool>("AllowHtml").HasColumnType("INTEGER");
                b.Property<bool>("AllowPing").HasColumnType("INTEGER");
                b.Property<int>("UserBandwidth").HasColumnType("INTEGER");
                b.Property<int>("UserTimeout").HasColumnType("INTEGER");
                b.Property<int>("MaxMessageLength").HasColumnType("INTEGER");
                b.Property<bool>("RememberChannel").HasColumnType("INTEGER");
                b.Property<int>("Slots").HasColumnType("INTEGER");
                b.Property<bool>("IsRunning").HasColumnType("INTEGER");
                b.HasKey("RowId");
                b.HasIndex("HostId");
                b.ToTable("VirtualServers");
            });

            modelBuilder.Entity("MumbleManager.Models.VirtualServerCache", b =>
            {
                b.HasOne("MumbleManager.Models.SshHostEntry", null)
                    .WithMany("CachedServers")
                    .HasForeignKey("HostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("MumbleManager.Models.SshHostEntry", b =>
            {
                b.Navigation("CachedServers");
            });
#pragma warning restore 612, 618
        }
    }
}
